const { useEffect, useMemo, useState } = React;
const h = React.createElement;
const Fragment = React.Fragment;
const E = (...children) => h(Fragment, null, ...children);

const NAV = [
  { group: 'Workspace', items: [{ key: 'dashboard', label: 'Dashboard', icon: '◈' }] },
  { group: 'AWS FinOps', items: [{ key: 'aws-costs', label: 'Cost Explorer', icon: '◒' }, { key: 'aws-waste', label: 'Waste', icon: '⌁' }, { key: 'aws-opt', label: 'Optimization', icon: '↗' }] },
  { group: 'Kubernetes', items: [{ key: 'k8s-overview', label: 'Overview', icon: '⬡' }, { key: 'k8s-workloads', label: 'Workloads', icon: '▦' }, { key: 'k8s-namespaces', label: 'Namespaces', icon: '◫' }, { key: 'k8s-nodes', label: 'Nodes', icon: '⊞' }, { key: 'k8s-opt', label: 'Optimization', icon: '↗' }] },
  { group: 'AI FinOps', items: [{ key: 'ai-overview', label: 'Overview', icon: '✦' }, { key: 'ai-usage', label: 'Token Usage', icon: '∿' }, { key: 'ai-models', label: 'Models', icon: '◎' }, { key: 'ai-applications', label: 'Applications', icon: '◌' }, { key: 'ai-opt', label: 'Optimization', icon: '↗' }, { key: 'ai-anomalies', label: 'Anomalies', icon: '△' }, { key: 'ai-unit', label: 'Unit Economics', icon: '∴' }] },
  { group: 'Controls', items: [{ key: 'forecast', label: 'Forecast', icon: '⌁' }, { key: 'governance', label: 'Governance', icon: '✓' }, { key: 'settings', label: 'Settings', icon: '⚙' }] },
];

const PAGE_INFO = {
  dashboard: ['Control plane', 'Cloud FinOps Control Plane', 'One view across infrastructure, Kubernetes allocation, and AI inference economics.'],
  'aws-costs': ['AWS FinOps / Cost Explorer', 'AWS cost visibility', 'Actual spend breakdown with dimensional views from the analysis engine.'],
  'aws-waste': ['AWS FinOps / Waste', 'AWS waste detection', 'Actionable waste findings with explicit estimates and risk context.'],
  'aws-opt': ['AWS FinOps / Optimization', 'AWS optimization', 'Review quick wins and validation steps before changing infrastructure.'],
  'k8s-overview': ['Kubernetes FinOps / Overview', 'Kubernetes cost allocation', 'Kubecost-style allocation built from requests, usage, and node economics.'],
  'k8s-workloads': ['Kubernetes FinOps / Workloads', 'Workload efficiency', 'Requests versus observed usage, with a configurable safety margin.'],
  'k8s-namespaces': ['Kubernetes FinOps / Namespaces', 'Namespace cost', 'Showback views for namespace owners and platform teams.'],
  'k8s-nodes': ['Kubernetes FinOps / Nodes', 'Node utilization', 'Identify underutilized capacity without blindly recommending consolidation.'],
  'k8s-opt': ['Kubernetes FinOps / Optimization', 'Kubernetes optimization', 'Rightsizing, replica efficiency, governance, and node opportunities.'],
  'ai-overview': ['AI FinOps / Overview', 'AI inference economics', 'Token volume, model mix, spend, and quality-aware evaluation opportunities.'],
  'ai-usage': ['AI FinOps / Token Usage', 'Normalized AI usage', 'Provider-neutral usage records for cost allocation and analysis.'],
  'ai-models': ['AI FinOps / Models', 'Model economics', 'Compare request volume, tokens, cost, and latency across providers.'],
  'ai-applications': ['AI FinOps / Applications', 'Application allocation', 'Allocate AI spend to the teams and environments creating the demand.'],
  'ai-opt': ['AI FinOps / Optimization', 'AI optimization', 'Evaluate routing, caching, context reduction, and output controls.'],
  'ai-anomalies': ['AI FinOps / Anomalies', 'AI cost anomalies', 'Surface spend and token changes that deserve investigation.'],
  'ai-unit': ['AI FinOps / Unit Economics', 'AI unit economics', 'Connect inference spend to tickets, documents, and business transactions.'],
  forecast: ['Controls / Forecast', 'Cost forecasting & scenario modeling', 'Scenario ranges based on historical spend and an explicit growth assumption.'],
  governance: ['Controls / Governance', 'Governance & policy', 'AWS tag compliance, Kubernetes resource policy, and AI budget posture.'],
  settings: ['Controls / Settings', 'Analysis settings', 'Configuration from config.yaml controls the thresholds used by the engine.'],
};

const ENDPOINTS = {
  dashboard: '/api/dashboard', 'aws-costs': '/api/costs', 'aws-waste': '/api/waste', 'aws-opt': '/api/recommendations?platform=aws',
  'k8s-overview': '/api/kubernetes/overview', 'k8s-workloads': '/api/kubernetes/workloads', 'k8s-namespaces': '/api/kubernetes/namespaces', 'k8s-nodes': '/api/kubernetes/nodes', 'k8s-opt': '/api/kubernetes/recommendations',
  'ai-overview': '/api/ai/overview', 'ai-usage': '/api/ai/usage', 'ai-models': '/api/ai/models', 'ai-applications': '/api/ai/applications', 'ai-opt': '/api/ai/recommendations', 'ai-anomalies': '/api/ai/anomalies', 'ai-unit': '/api/ai/unit-economics',
  forecast: '/api/forecast', governance: '/api/governance', settings: '/api/settings',
};

const money = (value) => '$' + Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 0 });
const money2 = (value) => '$' + Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const number = (value) => Number(value || 0).toLocaleString();
const tokens = (value) => { const n = Number(value || 0); if (n >= 1000000) return (n / 1000000).toFixed(n >= 10000000 ? 0 : 1) + 'M'; if (n >= 1000) return (n / 1000).toFixed(0) + 'K'; return number(n); };
const pct = (value) => Number(value || 0).toFixed(1) + '%';

function Icon({ children }) { return h('span', { className: 'nav-icon', 'aria-hidden': 'true' }, children); }
function Metric({ label, value, note, tone = '' }) { return h('div', { className: 'metric-card' }, h('div', { className: 'metric-label' }, label), h('div', { className: 'metric-value ' + tone }, value), h('div', { className: 'metric-delta ' + (note && note.startsWith('-') ? 'neutral' : '') }, note || 'Calculated from current data')); }
function Card({ title, meta, children, className = '' }) { return h('section', { className: 'card ' + className }, h('div', { className: 'card-title' }, h('h2', null, title), h('span', null, meta || '')), children); }
function Badge({ children, type = '' }) { return h('span', { className: 'severity ' + type }, children); }
function PlatformTag({ children }) { return h('span', { className: 'platform-tag' }, children); }
function Bar({ value, max = 100, color = 'var(--cyan)' }) { return h('div', { className: 'progress' }, h('div', { style: { width: Math.min(100, Math.max(0, Number(value || 0) / max * 100)) + '%', background: color } })); }
function Warning({ warnings }) { if (!warnings || !warnings.length) return null; return h('div', { className: 'warning' }, h('div', null, h('strong', null, 'Partial data warning'), warnings.map((w, i) => h('div', { key: i }, w.service + ': ' + w.message)))); }

function LineChart({ history = [], keys = ['total'], colors = ['var(--cyan)'] }) {
  if (!history.length) return h('div', { className: 'empty' }, 'No historical data available.');
  const width = 700, height = 205, padX = 32, padY = 20;
  const values = history.flatMap((point) => keys.map((key) => Number(point[key] || 0)));
  const max = Math.max(...values, 1), min = Math.min(...values, 0), range = max - min || 1;
  const x = (i) => padX + i * ((width - padX * 2) / Math.max(1, history.length - 1));
  const y = (v) => height - padY - ((v - min) / range) * (height - padY * 2);
  return h('div', { className: 'chart' }, h('svg', { viewBox: `0 0 ${width} ${height}`, role: 'img', 'aria-label': 'Cost trend chart' }, [0, .5, 1].map((grid, i) => h('line', { key: 'g' + i, className: 'axis', x1: padX, y1: y(min + range * grid), x2: width - padX, y2: y(min + range * grid) })), keys.map((key, k) => h('polyline', { key, fill: 'none', stroke: colors[k], strokeWidth: '3', strokeLinecap: 'round', strokeLinejoin: 'round', points: history.map((point, i) => `${x(i)},${y(Number(point[key] || 0))}`).join(' ') })), history.map((point, i) => i % Math.ceil(history.length / 6) === 0 ? h('text', { key: 't' + i, x: x(i), y: height - 2, className: 'axis-label', textAnchor: 'middle' }, point.period.slice(5)) : null)), h('div', { className: 'legend' }, keys.map((key, i) => h('span', { key }, h('i', { style: { background: colors[i] } }), key === 'total' ? 'Total spend' : key))));
}

function Doughnut({ items }) {
  const total = items.reduce((sum, item) => sum + Number(item.spend || item.cost || 0), 0) || 1;
  let offset = 0;
  const colors = ['var(--cyan)', 'var(--blue)', 'var(--purple)', 'var(--amber)', 'var(--lime)', 'var(--red)'];
  const segments = items.map((item, i) => { const amount = Number(item.spend || item.cost || 0); const start = offset; offset += amount / total * 100; return h('div', { key: i, className: 'platform-row' }, h('div', { className: 'platform-name' }, h('span', { className: 'platform-dot', style: { background: colors[i % colors.length] } }), item.name || item.model), h(Bar, { value: amount, max: Math.max(...items.map(x => Number(x.spend || x.cost || 0)), 1), color: colors[i % colors.length] }), h('div', { className: 'platform-amount' }, money(amount))); });
  return h('div', { className: 'platform-list' }, segments);
}

function RecommendationTable({ items, onExplain }) {
  if (!items || !items.length) return h('div', { className: 'empty' }, 'No findings match the current thresholds.');
  return h('table', { className: 'data-table' }, h('thead', null, h('tr', null, h('th', null, 'Priority'), h('th', null, 'Platform'), h('th', null, 'Finding'), h('th', { className: 'right' }, 'Est. savings'), h('th', null, 'Confidence'), h('th', null, ''))), h('tbody', null, items.map((item) => h('tr', { key: item.id }, h('td', null, h(Badge, { type: item.priority }, item.priority)), h('td', null, h(PlatformTag, null, item.platform)), h('td', null, h('div', null, item.issue), h('div', { className: 'small' }, item.recommendation)), h('td', { className: 'right mono' }, money2(item.estimated_monthly_savings)), h('td', null, item.confidence), h('td', null, h('button', { className: 'action-link', onClick: () => onExplain && onExplain(item) }, 'Explain')))))); }

function Table({ headers, rows, empty = 'No data available.' }) { if (!rows || !rows.length) return h('div', { className: 'empty' }, empty); return h('table', { className: 'data-table' }, h('thead', null, h('tr', null, headers.map((header, i) => h('th', { key: i, className: header.right ? 'right' : '' }, header.label || header))), h('tbody', null, rows.map((row, ri) => h('tr', { key: row.key || ri }, headers.map((header, ci) => h('td', { key: ci, className: header.right ? 'right' : '' }, typeof header.render === 'function' ? header.render(row) : row[header.key]))))))); }

function Dashboard({ data, onExplain }) {
  const s = data.summary || {};
  return E(h('div', { className: 'metrics' }, h(Metric, { label: 'Monthly cloud + AI spend', value: money(s.total_monthly_spend), note: 'AWS + Kubernetes + AI' }), h(Metric, { label: 'Potential monthly savings', value: money(s.potential_monthly_savings), note: `${s.finding_count || 0} deduplicated findings` }), h(Metric, { label: 'Spend identified as waste', value: pct(s.waste_pct), note: 'Unique opportunities only' }), h(Metric, { label: 'Overall efficiency', value: pct(s.overall_efficiency), note: 'Allocation and usage posture' })), h('div', { className: 'grid two-col' }, h(Card, { title: 'Total cost trend', meta: '12 months' }, h(LineChart, { history: data.history, keys: ['total'], colors: ['var(--cyan)'] })), h(Card, { title: 'Spend by platform', meta: 'Current month' }, h(Doughnut, { items: data.platforms || [] }))), h('div', { className: 'grid two-col section-gap' }, h(Card, { title: 'Platform posture', meta: 'Spend / potential savings' }, h(Table, { headers: [{ label: 'Platform', key: 'name', render: (r) => h(PlatformTag, null, r.name) }, { label: 'Spend', key: 'spend', right: true, render: (r) => money(r.spend) }, { label: 'Potential savings', key: 'savings', right: true, render: (r) => money(r.savings) }], rows: data.platforms || [] })), h(Card, { title: 'Top opportunities', meta: 'Deduplicated' }, h(RecommendationTable, { items: data.top_opportunities || [], onExplain }))), h('div', { className: 'callout section-gap' }, h('strong', null, 'Measurement before remediation'), 'Every savings number is an estimate with confidence and risk. The control plane keeps one stable identity per opportunity so waste and optimization findings cannot be added twice.'));
}

function AWSPage({ page, data, onExplain }) {
  if (page === 'aws-costs') return E(h('div', { className: 'metrics' }, h(Metric, { label: 'Monthly AWS spend', value: money(data.total_monthly_cost), note: 'Cost Explorer or demo data' }), h(Metric, { label: 'Services tracked', value: number(Object.keys(data.by_service || {}).length), note: 'Grouped by service' }), h(Metric, { label: 'Regions tracked', value: number(Object.keys(data.by_region || {}).length), note: 'Configured scope' }), h(Metric, { label: 'Teams allocated', value: number(Object.keys(data.by_team || {}).length), note: 'From cost allocation tags' })), h('div', { className: 'grid two-col' }, h(Card, { title: 'Service breakdown', meta: 'USD / month' }, h(Table, { headers: [{ label: 'Service', key: 'name' }, { label: 'Cost', key: 'value', right: true, render: (r) => money2(r.value) }, { label: 'Share', key: 'share', right: true, render: (r) => pct(r.share) }], rows: Object.entries(data.by_service || {}).map(([name, value]) => ({ name, value, share: value / data.total_monthly_cost * 100 })) })), h(Card, { title: 'Allocation views', meta: 'Tag-derived' }, h(Table, { headers: [{ label: 'Dimension', key: 'name' }, { label: 'Cost', key: 'value', right: true, render: (r) => money2(r.value) }], rows: Object.entries(data.by_team || {}).map(([name, value]) => ({ name: 'Team · ' + name, value })).concat(Object.entries(data.by_environment || {}).map(([name, value]) => ({ name: 'Environment · ' + name, value }))) }))), h(Card, { title: 'Regional allocation', meta: 'USD / month', className: 'section-gap' }, h(Table, { headers: [{ label: 'Region', key: 'name' }, { label: 'Cost', key: 'value', right: true, render: (r) => money2(r.value) }], rows: Object.entries(data.by_region || {}).map(([name, value]) => ({ name, value })) })));
  const findings = data.findings || data.recommendations || [];
  return E(h('div', { className: 'metrics' }, h(Metric, { label: page === 'aws-waste' ? 'Identified waste' : 'Potential savings', value: money(data.total_waste || data.total_potential_savings), note: 'Unique AWS opportunities' }), h(Metric, { label: 'Findings', value: number(findings.length), note: 'With explainable rationale' }), h(Metric, { label: 'High priority', value: number(findings.filter((x) => x.priority === 'HIGH').length), note: 'Review first' }), h(Metric, { label: 'Risk posture', value: 'Validate', note: 'No auto-remediation' })), h(Card, { title: page === 'aws-waste' ? 'Waste findings' : 'AWS recommendations', meta: 'Estimated monthly savings' }, h(RecommendationTable, { items: findings, onExplain })));
}

function K8sPage({ page, data, onExplain }) {
  if (page === 'k8s-overview') { const c = data.cluster || {}; return E(h('div', { className: 'metrics' }, h(Metric, { label: 'Cluster cost', value: money(c.monthly_cost), note: c.name || 'Demo cluster' }), h(Metric, { label: 'Allocated cost', value: money(c.allocated_cost), note: 'Workload + namespace views' }), h(Metric, { label: 'Unallocated cost', value: money(c.unallocated_cost), note: 'Not treated as savings' }), h(Metric, { label: 'Allocation efficiency', value: pct(c.efficiency), note: 'Allocated / cluster cost' })), h('div', { className: 'grid two-col' }, h(Card, { title: 'Node utilization', meta: 'CPU / memory' }, h(Table, { headers: [{ label: 'Node', key: 'name' }, { label: 'CPU', key: 'cpu', right: true, render: (r) => pct(r.cpu_utilization * 100) }, { label: 'Memory', key: 'mem', right: true, render: (r) => pct(r.memory_utilization * 100) }, { label: 'Monthly cost', key: 'cost', right: true, render: (r) => money(r.monthly_cost) }], rows: (data.nodes || []).map((r) => ({ ...r, cpu: r.cpu_utilization, mem: r.memory_utilization, cost: r.monthly_cost })) })), h(Card, { title: 'Namespace allocation', meta: 'Current month' }, h(Table, { headers: [{ label: 'Namespace', key: 'namespace' }, { label: 'Cost', key: 'monthly_cost', right: true, render: (r) => money(r.monthly_cost) }, { label: 'Share', key: 'cluster_cost_pct', right: true, render: (r) => pct(r.cluster_cost_pct) }], rows: data.namespaces || [] }))), h(Card, { title: 'Top optimization opportunities', meta: 'Safe evaluation path', className: 'section-gap' }, h(RecommendationTable, { items: (data.recommendations || []).filter((x) => x.estimated_monthly_savings > 0).slice(0, 5), onExplain })) ); }
  if (page === 'k8s-workloads') return h(Card, { title: 'Workload requests vs actual usage', meta: 'CPU cores / GiB' }, h(Table, { headers: [{ label: 'Workload', key: 'name' }, { label: 'Namespace', key: 'namespace' }, { label: 'CPU req / used', key: 'cpu', right: true, render: (r) => `${r.cpu_request} / ${r.cpu_usage}` }, { label: 'Memory req / used', key: 'mem', right: true, render: (r) => `${r.memory_request} / ${r.memory_usage} GiB` }, { label: 'Efficiency', key: 'eff', right: true, render: (r) => pct(r.efficiency * 100) }, { label: 'Savings', key: 'estimated_savings', right: true, render: (r) => money(r.estimated_savings) }], rows: data.workloads || [] }));
  if (page === 'k8s-namespaces') return h(Card, { title: 'Namespace showback', meta: 'Cluster cost allocation' }, h(Table, { headers: [{ label: 'Namespace', key: 'namespace' }, { label: 'Cost', key: 'monthly_cost', right: true, render: (r) => money(r.monthly_cost) }, { label: 'CPU cost', key: 'cpu_cost', right: true, render: (r) => money(r.cpu_cost) }, { label: 'Memory cost', key: 'memory_cost', right: true, render: (r) => money(r.memory_cost) }, { label: 'Workloads', key: 'workload_count', right: true }, { label: 'Pods', key: 'pod_count', right: true }, { label: 'Share', key: 'cluster_cost_pct', right: true, render: (r) => pct(r.cluster_cost_pct) }], rows: data.namespaces || [] }));
  if (page === 'k8s-nodes') return h(Card, { title: 'Node capacity posture', meta: 'Utilization is not a consolidation proof' }, h(Table, { headers: [{ label: 'Node', key: 'name' }, { label: 'Type', key: 'instance_type' }, { label: 'CPU util.', key: 'cpu_utilization', right: true, render: (r) => pct(r.cpu_utilization * 100) }, { label: 'Memory util.', key: 'memory_utilization', right: true, render: (r) => pct(r.memory_utilization * 100) }, { label: 'Monthly cost', key: 'monthly_cost', right: true, render: (r) => money(r.monthly_cost) }, { label: 'Status', key: 'status', render: (r) => r.utilization < .3 ? h(Badge, { type: 'MEDIUM' }, 'UNDERUTILIZED') : h(Badge, { type: 'LOW' }, 'ACTIVE') }], rows: data.nodes || [] }));
  return h(Card, { title: 'Kubernetes optimization queue', meta: 'Requests, replicas, and nodes' }, h(RecommendationTable, { items: data.recommendations || [], onExplain }));
}

function AIPage({ page, data, onExplain }) {
  if (page === 'ai-overview') return E(h('div', { className: 'metrics' }, h(Metric, { label: 'Monthly AI spend', value: money(data.monthly_spend), note: 'Normalized provider usage' }), h(Metric, { label: 'Total tokens', value: tokens(data.total_tokens), note: `${tokens(data.input_tokens)} input / ${tokens(data.output_tokens)} output` }), h(Metric, { label: 'Cost / 1K tokens', value: '$' + Number(data.cost_per_1k_tokens || 0).toFixed(3), note: 'Blended across models' }), h(Metric, { label: 'Potential savings', value: money(data.potential_savings), note: 'Evaluation opportunities' })), h('div', { className: 'grid two-col' }, h(Card, { title: 'AI spend trend', meta: 'Platform history' }, h(LineChart, { history: data.history || [], keys: ['AI'], colors: ['var(--purple)'] })), h(Card, { title: 'Spend by model', meta: 'Current month' }, h(Doughnut, { items: data.models || [] }))), h(Card, { title: 'AI optimization opportunities', meta: 'Quality and risk must be validated', className: 'section-gap' }, h(RecommendationTable, { items: (data.recommendations || []).filter((x) => x.estimated_monthly_savings > 0), onExplain })) );
  if (page === 'ai-usage') return h(Card, { title: 'Normalized token usage', meta: 'Provider-neutral AIUsage records' }, h(Table, { headers: [{ label: 'Application', key: 'application' }, { label: 'Model', key: 'model' }, { label: 'Requests', key: 'request_count', right: true, render: (r) => number(r.request_count) }, { label: 'Input', key: 'input_tokens', right: true, render: (r) => tokens(r.input_tokens) }, { label: 'Output', key: 'output_tokens', right: true, render: (r) => tokens(r.output_tokens) }, { label: 'Cost', key: 'cost', right: true, render: (r) => money(r.cost) }, { label: 'Latency', key: 'latency_ms', right: true, render: (r) => Math.round(r.latency_ms) + ' ms' }], rows: data.usage || [] }));
  if (page === 'ai-models') return h(Card, { title: 'Model economics', meta: 'Provider and model mix' }, h(Table, { headers: [{ label: 'Provider', key: 'provider' }, { label: 'Model', key: 'model' }, { label: 'Requests', key: 'requests', right: true, render: (r) => number(r.requests) }, { label: 'Tokens', key: 'total_tokens', right: true, render: (r) => tokens(r.total_tokens) }, { label: 'Cost', key: 'cost', right: true, render: (r) => money(r.cost) }, { label: 'Cost / 1K', key: 'cost_per_1k_tokens', right: true, render: (r) => '$' + Number(r.cost_per_1k_tokens).toFixed(3) }, { label: 'Latency', key: 'latency_ms', right: true, render: (r) => Math.round(r.latency_ms) + ' ms' }], rows: data.models || [] }));
  if (page === 'ai-applications') return h(Card, { title: 'Cost by application', meta: 'Team and environment allocation' }, h(Table, { headers: [{ label: 'Application', key: 'application' }, { label: 'Team', key: 'team' }, { label: 'Environment', key: 'environment' }, { label: 'Requests', key: 'requests', right: true, render: (r) => number(r.requests) }, { label: 'Tokens', key: 'tokens', right: true, render: (r) => tokens(r.tokens) }, { label: 'Cost', key: 'cost', right: true, render: (r) => money(r.cost) }, { label: 'Cost / request', key: 'cost_per_request', right: true, render: (r) => '$' + Number(r.cost_per_request).toFixed(4) }], rows: data.applications || [] }));
  if (page === 'ai-anomalies') return h(Card, { title: 'Anomaly queue', meta: 'Investigate before acting' }, h(Table, { headers: [{ label: 'Severity', key: 'severity', render: (r) => h(Badge, { type: r.severity }, r.severity) }, { label: 'Anomaly', key: 'title' }, { label: 'Primary cause', key: 'primary_cause' }, { label: 'Estimated additional cost', key: 'estimated_additional_cost', right: true, render: (r) => money(r.estimated_additional_cost) }, { label: 'Status', key: 'status' }], rows: data.anomalies || [] }));
  if (page === 'ai-unit') return h('div', { className: 'grid mini-grid' }, (data.metrics || []).map((item) => h('div', { className: 'mini-stat', key: item.metric }, h('div', { className: 'metric-label' }, item.metric), h('div', { className: 'metric-value' }, '$' + Number(item.value || 0).toFixed(3)), h('div', { className: 'small' }, item.unit))));
  return h(Card, { title: 'AI optimization queue', meta: 'Evaluation recommendations' }, h(RecommendationTable, { items: data.recommendations || [], onExplain }));
}

function Forecast({ data }) { return E(h('div', { className: 'metrics' }, h(Metric, { label: 'Method', value: 'Scenario', note: 'Not ML' }), h(Metric, { label: 'Growth assumption', value: pct(Number(data.growth_rate || 0) * 100), note: 'Configurable in settings' }), h(Metric, { label: 'Horizon', value: number(data.horizon_months) + ' mo', note: 'Projection window' }), h(Metric, { label: 'Next month baseline', value: money(data.projections && data.projections[0] && data.projections[0].baseline), note: 'Baseline scenario' })), h(Card, { title: 'Historical spend', meta: 'Platform history' }, h(LineChart, { history: data.historical || [], keys: ['total'], colors: ['var(--blue)'] })), h(Card, { title: 'Scenario projections', meta: 'Baseline / conservative / aggressive', className: 'section-gap' }, h(Table, { headers: [{ label: 'Month', key: 'month' }, { label: 'Baseline', key: 'baseline', right: true, render: (r) => money(r.baseline) }, { label: 'Conservative', key: 'conservative', right: true, render: (r) => money(r.conservative) }, { label: 'Aggressive', key: 'aggressive', right: true, render: (r) => money(r.aggressive) }], rows: data.projections || [] }))); }

function Governance({ data }) { const aws = data.aws || {}, k8s = data.kubernetes || {}, ai = data.ai || {}; return E(h('div', { className: 'grid mini-grid' }, h('div', { className: 'mini-stat' }, h('div', { className: 'metric-label' }, 'AWS tag compliance'), h('div', { className: 'metric-value' }, pct(aws.overall)), h(Bar, { value: aws.overall, color: 'var(--cyan)' })), h('div', { className: 'mini-stat' }, h('div', { className: 'metric-label' }, 'K8s requests'), h('div', { className: 'metric-value' }, pct(k8s.requests_compliance)), h(Bar, { value: k8s.requests_compliance, color: 'var(--blue)' })), h('div', { className: 'mini-stat' }, h('div', { className: 'metric-label' }, 'AI budget posture'), h('div', { className: 'metric-value' }, pct(ai.budget_compliance)), h(Bar, { value: ai.budget_compliance, color: 'var(--purple)' }))), h('div', { className: 'grid two-col' }, h(Card, { title: 'Required AWS tags', meta: 'From config.yaml' }, h('div', { className: 'tag-row' }, (data.required_tags || []).map((tag) => h('span', { className: 'tag', key: tag }, tag))), h('div', { className: 'section-gap' }, h(Table, { headers: [{ label: 'Tag', key: 'tag' }, { label: 'Compliance', key: 'value', right: true, render: (r) => pct(r.value) }], rows: Object.entries(aws.by_tag || {}).map(([tag, value]) => ({ tag, value })) }))), h(Card, { title: 'Policy exceptions', meta: 'Requires owner review' }, h('div', { className: 'small' }, 'Kubernetes workloads without requests'), h('div', { className: 'tag-row section-gap' }, (k8s.workloads_without_requests || []).map((item) => h('span', { className: 'tag', key: item }, item))), h('div', { className: 'small section-gap' }, 'Kubernetes workloads without limits'), h('div', { className: 'tag-row section-gap' }, (k8s.workloads_without_limits || []).map((item) => h('span', { className: 'tag', key: item }, item))), h('div', { className: 'callout section-gap' }, 'AI budget utilization is ', pct(ai.budget_utilization), ' against a ', money(ai.monthly_budget), ' monthly budget.')))); }

function Settings({ data, onSaved }) { const [values, setValues] = useState(data.settings || {}); useEffect(() => setValues(data.settings || {}), [data]); const fields = [['idle_cpu_threshold', 'AWS idle CPU threshold (%)'], ['idle_days', 'AWS idle days'], ['old_snapshot_days', 'Old snapshot age (days)'], ['cpu_efficiency_threshold', 'K8s CPU efficiency threshold'], ['memory_efficiency_threshold', 'K8s memory efficiency threshold'], ['node_utilization_threshold', 'K8s node utilization threshold'], ['safety_margin', 'K8s safety margin'], ['monthly_budget', 'AI monthly budget ($)'], ['alert_threshold', 'AI alert threshold (%)'], ['high_cost_request', 'AI high-cost request ($)'], ['forecast_horizon_months', 'Forecast horizon (months)'], ['growth_rate', 'Forecast growth assumption']]; return h(Card, { title: 'Runtime analysis settings', meta: 'PATCH /api/settings' }, h('div', { className: 'form-grid' }, fields.map(([key, label]) => h('label', { className: 'form-label', key }, label, h('input', { type: 'number', step: key.includes('threshold') || key === 'safety_margin' || key === 'growth_rate' ? '0.01' : '1', value: values[key] ?? '', onChange: (e) => setValues({ ...values, [key]: Number(e.target.value) }) })))), h('button', { className: 'save-button', onClick: async () => { const response = await fetch('/api/settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) }); if (response.ok) onSaved(await response.json()); } }, 'Save configuration'), h('p', { className: 'footer-note' }, 'Changes are written to config.yaml. Required AWS tags remain an explicit governance policy; credentials are never stored by this UI.'));
}

function ExplainModal({ item, onClose }) { if (!item) return null; return h('div', { style: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,.65)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20, zIndex: 5 }, onClick: onClose }, h('div', { className: 'card', style: { maxWidth: 600, width: '100%' }, onClick: (e) => e.stopPropagation() }, h('div', { className: 'card-title' }, h('h2', null, 'Why this recommendation?'), h('button', { className: 'action-link', onClick: onClose }, 'Close')), h('div', { className: 'tag-row' }, h(PlatformTag, null, item.platform), h(Badge, { type: item.priority }, item.priority), h('span', { className: 'tag' }, item.confidence + ' confidence'), h('span', { className: 'tag' }, item.risk + ' risk')), h('p', { style: { color: '#d6e0ec', fontSize: 12, lineHeight: 1.6 } }, item.explanation), h('div', { className: 'callout' }, h('strong', null, 'Estimated monthly savings'), money2(item.estimated_monthly_savings), h('div', { className: 'small' }, item.recommendation)))); }

function App() {
  const [page, setPage] = useState('dashboard');
  const [data, setData] = useState(null);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [mode, setMode] = useState('demo');
  const [updated, setUpdated] = useState('');
  const [explain, setExplain] = useState(null);
  const load = async () => { setLoading(true); setError(''); try { const [response, modeResponse] = await Promise.all([fetch(ENDPOINTS[page]), fetch('/api/mode')]); if (!response.ok) throw new Error('API returned ' + response.status); const payload = await response.json(); const modePayload = await modeResponse.json(); setData(payload); setMode(modePayload.mode || 'demo'); setUpdated(payload.last_updated || new Date().toISOString()); } catch (e) { setError(e.message || 'Unable to load control-plane data.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [page]);
  const [eyebrow, title, subtitle] = PAGE_INFO[page];
  const renderPage = () => { if (loading) return h('div', { className: 'card empty' }, 'Loading analysis…'); if (error) return h('div', { className: 'warning' }, h('div', null, h('strong', null, 'API unavailable'), error)); if (!data) return null; if (page === 'dashboard') return h(Dashboard, { data, onExplain: setExplain }); if (page.startsWith('aws-')) return h(AWSPage, { page, data, onExplain: setExplain }); if (page.startsWith('k8s-')) return h(K8sPage, { page, data, onExplain: setExplain }); if (page.startsWith('ai-')) return h(AIPage, { page, data, onExplain: setExplain }); if (page === 'forecast') return h(Forecast, { data }); if (page === 'governance') return h(Governance, { data }); if (page === 'settings') return h(Settings, { data, onSaved: (saved) => { setData(saved); setUpdated(saved.last_updated || new Date().toISOString()); } }); return null; };
  return h('div', { className: 'app' }, h('aside', { className: 'sidebar' }, h('div', { className: 'brand' }, h('div', { className: 'brand-mark' }, 'CF'), h('div', null, h('div', { className: 'brand-title' }, 'Cloud FinOps'), h('div', { className: 'brand-sub' }, 'CONTROL PLANE'))), NAV.map((section) => h('div', { key: section.group }, h('div', { className: 'nav-label' }, section.group), section.items.map((item) => h('button', { key: item.key, className: 'nav-item ' + (page === item.key ? 'active' : ''), onClick: () => setPage(item.key) }, h(Icon, null, item.icon), item.label)))), h('div', { className: 'sidebar-footer' }, 'Three optimization loops.<br/>AWS infrastructure · Kubernetes allocation · AI inference economics.')), h('main', { className: 'main' }, h('header', { className: 'topbar' }, h('div', { className: 'top-context' }, h('div', { className: 'context-pill' }, h('span', { className: 'status-dot' }), h('strong', null, mode.toUpperCase()), 'mode'), h('div', { className: 'context-pill' }, 'Account ', h('strong', null, data && data.account_id ? data.account_id : 'DEMO-123456789')), h('div', { className: 'context-pill' }, 'Region ', h('strong', null, 'us-east-1'))), h('div', { className: 'top-actions' }, h('span', { className: 'updated' }, updated ? 'UPDATED ' + new Date(updated).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : ''), h('button', { className: 'refresh', onClick: load }, '↻ Refresh'))), h('div', { className: 'content' }, h('div', { className: 'page-heading' }, h('div', null, h('div', { className: 'kicker' }, eyebrow), h('h1', null, title), h('p', null, subtitle)), h('div', { className: 'badge' }, mode === 'demo' ? 'No credentials required' : 'Live connectors')), data && h(Warning, { warnings: data.warnings }), renderPage())), h(ExplainModal, { item: explain, onClose: () => setExplain(null) }));
}

ReactDOM.createRoot(document.getElementById('root')).render(h(App));
